#!/bin/bash

if [ ! -d "venv" ]; then
    echo "Error: Virtual environment 'venv' not found.
       Run 'python3 wizard.py'"
    exit 1
fi

source venv/bin/activate

args_string=""
for arg in "$@"; do
    args_string+=" $arg"
done

python explore.py make $args_string

deactivate
