#!/bin/bash

if [ ! -d "venv" ]; then
    echo "Error: Virtual environment 'venv' not found.
       Run 'python3 wizard.py'"
    exit 1
fi

source venv/bin/activate

python src/explore.py make $@

deactivate
